### ISSUE TITLE
月历组件

### ISSUE THREAD

**Issue by TechQuery** [idea2app/Idea-React#35]
## 界面参考

https://bootstrap.web-cell.dev/#components/calendar/month-calender

## 代码参考

https://github.com/EasyWebApp/BootCell/blob/master/source/Calendar/MonthCalendar.tsx

**Comment by wangrunlin** [comment]
- 可增加添加日历、订阅日历功能

**Comment by wangrunlin** [comment]
是要按照参考在开源社官网重新写一个新的月历组件吗？

**Comment by wangrunlin** [comment]
这里是参考之前的代码进行重写吗？

**Comment by TechQuery** [comment]
> 这里是参考之前的代码进行重写吗？

当然，组件引擎都不一样。
