### ISSUE TITLE
日历视图 3 bug ： 单元格没做宽度限制，导致宽度不一致；换行符不支持 

### ISSUE THREAD

**Issue by huoyueyuyuan** [idea2app/Idea-React#48]
![88c73504-2581-43bd-81d7-262169c967bb](https://github.com/idea2app/Idea-React/assets/22514503/830921d5-4a98-44e6-9b90-750cdde2086d)

content："KCC@杭州-在初秋，来一场智力与体能的比拼 &&& COSCon‘22@Dalian | 中国开源年会大连分会场邀您组局聊聊"
或者 ："KCC SINGAPRE 助力2023 MetaTrust杯新加坡Web3 CTF安全竞赛正式启动 &&& 活动推荐｜8.16 新加坡 2023 国际开源节云原生技术沙龙开启报名 &&& CommunityOverCode Asia 2023 议程全览，不容错过的阿帕奇技术盛宴"

**Comment by huoyueyuyuan** [comment]
![image](https://github.com/idea2app/Idea-React/assets/22514503/9ea1e80b-3ae9-40cc-92e7-1c19b8873af1)
不支持换行符

**Comment by huoyueyuyuan** [comment]
![image](https://github.com/idea2app/Idea-React/assets/22514503/6aba6c76-4bd4-47c6-9890-a4a8a8b78b62)

测试数据 ：
[
  {
    date: 2023-08-21T11:11:00.000Z,
    content: 'KCC@杭州-在初秋，来一场智力与体能的比拼\nCOSCon‘22@Dalian | 中国开源年会大连分会场邀您组局聊聊'
  },
  {
    date: 2023-08-13T13:00:00.000Z,
    content: 'KCC SINGAPRE 助力2023 MetaTrust杯新加坡Web3 CTF安全竞赛正式启动\n' +
      '活动推荐｜8.16 新加坡 2023 国际开源节云原生技术沙龙开启报名\n' +
      'CommunityOverCode Asia 2023 议程全览，不容错过的阿帕奇技术盛宴'
  },
  { date: 2023-02-22T13:05:00.000Z, content: '深圳硬件黑客松精彩回顾' },
  {
    date: 2022-10-27T13:30:00.000Z,
    content: "COSCon'22论坛集锦 1+16个论坛就等你了！"
  },
  {
    date: 2022-10-25T13:06:00.000Z,
    content: "COSCon'22@Shanghai | 上海站开源集市召集令\nCOSCon'22@Chengdu | 成都分会场等你赴约"
  },
  {
    date: 2022-10-22T13:00:00.000Z,
    content: "倒计时 7 天，COSCon'22 会议议程全览，精彩亮点抢鲜看！"
  }
]

**Comment by TechQuery** [comment]
> ![88c73504-2581-43bd-81d7-262169c967bb](https://github.com/idea2app/Idea-React/assets/22514503/830921d5-4a98-44e6-9b90-750cdde2086d)
> 
> content："KCC@杭州-在初秋，来一场智力与体能的比拼 &&& COSCon‘22@Dalian | 中国开源年会大连分会场邀您组局聊聊"
> 或者 ："KCC SINGAPRE 助力2023 MetaTrust杯新加坡Web3 CTF安全竞赛正式启动 &&& 活动推荐｜8.16 新加坡 2023 国际开源节云原生技术沙龙开启报名 &&& CommunityOverCode Asia 2023 议程全览，不容错过的阿帕奇技术盛宴"

这一条请将代码推到线上，并发给我预览链接。

**Comment by TechQuery** [comment]
> ![image](https://github.com/idea2app/Idea-React/assets/22514503/9ea1e80b-3ae9-40cc-92e7-1c19b8873af1)
> 不支持换行符

HTML 本身不支持文本中的换行符，只能通过换行标签或者 CSS 样式实现。

此处我可能会考虑在组件内用 Markdown 解析库来生成 HTML。

**Comment by huoyueyuyuan** [comment]
> > ![88c73504-2581-43bd-81d7-262169c967bb](https://user-images.githubusercontent.com/22514503/269866566-830921d5-4a98-44e6-9b90-750cdde2086d.jpeg)
> > content："KCC@杭州-在初秋，来一场智力与体能的比拼 &&& COSCon‘22@Dalian | 中国开源年会大连分会场邀您组局聊聊"
> > 或者 ："KCC SINGAPRE 助力2023 MetaTrust杯新加坡Web3 CTF安全竞赛正式启动 &&& 活动推荐｜8.16 新加坡 2023 国际开源节云原生技术沙龙开启报名 &&& CommunityOverCode Asia 2023 议程全览，不容错过的阿帕奇技术盛宴"
> 
> 这一条请将代码推到线上，并发给我预览链接。

记录显示不全的，已经解决，是我写了 2个处理 ， 传错了
